// <auto-generated />
namespace app_com_bog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Sales_Model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Sales_Model));
        
        string IMigrationMetadata.Id
        {
            get { return "201708050159287_Sales_Model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
